# Generated by Django 2.2.7 on 2019-11-15 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('date_order', models.DateField(blank=True, null=True)),
                ('date_incident', models.DateField(blank=True, null=True, verbose_name='Incident')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_1', models.CharField(max_length=200)),
                ('char_2', models.CharField(max_length=200)),
                ('char_3', models.CharField(max_length=200)),
                ('boolean_1', models.BooleanField()),
                ('boolean_2', models.BooleanField()),
                ('boolean_3', models.BooleanField()),
                ('boolean_4', models.BooleanField()),
                ('boolean_5', models.BooleanField()),
                ('boolean_6', models.BooleanField()),
                ('boolean_7', models.BooleanField()),
                ('integer_1', models.IntegerField()),
                ('integer_2', models.IntegerField()),
                ('image_1', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('image_2', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('file_1', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.Author')),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('second_name', models.CharField(help_text='Enter second name', max_length=20)),
                ('telephon', models.CharField(help_text='Enter telephones number', max_length=10)),
                ('email', models.CharField(help_text='Enter email adderess', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular claim across whole reestry', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('i', 'init'), ('s', 'sent'), ('e', 'editional'), ('p', 'prepared'), ('d', 'delivered')], default='i', max_length=1)),
                ('claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.Claim')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
