# Generated by Django 2.2.7 on 2019-11-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('telephon', models.CharField(help_text='Enter telephones number', max_length=10)),
                ('email', models.CharField(help_text='Enter email adderess', max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('date_order', models.DateField(blank=True, null=True)),
                ('date_incident', models.DateField(blank=True, null=True, verbose_name='Incident')),
            ],
        ),
        migrations.DeleteModel(
            name='General',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='claim',
            name='witness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.Witness'),
        ),
    ]
