# Generated by Django 2.2.7 on 2019-11-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0002_auto_20191115_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='char_3',
            new_name='title',
        ),
    ]
