# Generated by Django 2.2.7 on 2019-11-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0003_auto_20191115_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='date_incident',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Incident'),
        ),
    ]
