# Generated by Django 2.2.7 on 2019-11-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0004_auto_20191115_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='char_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='char_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='integer_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='integer_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
