# Generated by Django 2.2.7 on 2019-11-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0005_auto_20191115_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='witness',
            options={'ordering': ['second_name']},
        ),
        migrations.AddField(
            model_name='claim',
            name='question',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
