# Generated by Django 2.2.7 on 2019-11-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0006_auto_20191115_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
